### ISSUE TITLE
[Feature request]: Update numpy version

### ISSUE THREAD

**Issue by arpit15** [Peter-van-Tol/pydantic-shapely#9]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read the documentation and couldn't find anything
- [X] The feature request is limited to combining Pydantic, Shapely and GeoJSON

### Description

Thanks for creating nice interface for integrating shapely objects. I find that the numpy version in the pypi release is too strict for my use-case. I am wondering if you have a reason to mark it strictly at `1.24.4`. My stack depends on `~1.26`. It would be great if the package requirements for this repository could be updated or made more relaxed. 

### Affected Components

- [X] GeometryField, including supported types, validation, and serialization.
- [ ] GeoJSON export and import

**Comment by Peter-van-Tol** [comment]
I'll ease the `numpy` requirement and release afixed version over this weekend.

**Comment by Peter-van-Tol** [comment]
Removed `numpy` from the dependencies all together, becuase it is part of the dependencies required by `shapely`. Moved the dependency to the development section  for now to have a smooth installing environment on Windows.

**Comment by Peter-van-Tol** [comment]
Fixed in version `1.0.0a3`, available on PyPi now! 🚀
